Repository kubernetes-sigs/aws-file-cache-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#8 Add container image workflow to publish images to ECR public repo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/cr.yaml
  .github/workflows/container-image.yaml
  Makefile
  charts/aws-file-cache-csi-driver/values.yaml
  deploy/kubernetes/base/controller-deployment.yaml
  deploy/kubernetes/base/node-daemonset.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: lgtm, cncf-cla: yes, approved, size/L

#10 Add initial index.yaml
  index.yaml
Labels: lgtm, cncf-cla: yes, size/XS

#11 gh workflows for helm chart release
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-request.md
  .github/cr.yaml
  .github/workflows/container-image.yaml
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#12 Release 0.1.0 part 1/3: README
  docs/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#13 Release 0.1.0 part 2/3: helm README
  charts/aws-file-cache-csi-driver/CHANGELOG.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#14 Release 0.1 part 3/3: Merge release-0.1 changes to main
  charts/aws-file-cache-csi-driver/CHANGELOG.md
  docs/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#15 Only push image to ECR on tagged release
  .github/workflows/container-image.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#17 Add index.yaml for helm 0.1.0
  index.yaml
Labels: lgtm, cncf-cla: yes, size/S

#18 Update README
  docs/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#19 Add detailed installation instructions and examples
  docs/README.md
Labels: lgtm, cncf-cla: yes, approved, size/L

#20 Change Pending time
  docs/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
